typography_spectrum: 0.6617022
color:
  saturation: 1
  brandStrength: 0.387563
  lightness: 1
  rhythmicContrast: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0
name: EmpreendedorJr
title: Empreendedor Jr.
description: Estágio em CEO
